theme: jekyll-theme-tactile
title: Ayesha Bhimdiwala
title: Ayesha Bhimdiwala
title: Ayesha Bhimdiwala
description: Graduate Data Science Student, Aspiring Data Scientist
url: "https://aysh20.github.io"
