theme: jekyll-theme-tactile
title: Ayesha Bhimdiwala
title: Ayesha Bhimdiwala
name: Ayesha Bhimdiwala
description: Graduate Data Science Student, Aspiring Data Scientist
avatar: https://aysh20.github.io/images/bestpic2018.jpg
url: "https://aysh20.github.io"
